### PR TITLE
Add commenting describing application version to saved spreadsheets

### LINKED ISSUE #89: DataHarmonizer Version Information in Output Files
I know there is currently discussion on how to add version metadata to DataHarmonizer output files; but while a more sophisticated implementation is being determined - perhaps for the time being commented metadata values should be added directly onto the spreadsheet (e.g. in one of the empty cells in the 'database identifiers' row) to ensure there is some version information on files for current users.

### PR DESCRIPTION
**Pull request by ivansg44**
Fixes #89.

### CODE REVIEW

**Comment by ivansg44** [comment]
image

@griffie Add a comment to cell B1 that describes the application version used when saving. Not sure where to, or if I even should, add a comment for exported GISAID and IRIDA files. Neither has empty header cells.

**Comment by griffie** [comment]
Hmm, I think having the DH version is important. The way you have it now works. For GISAID I don't think they need to know this info so if the top line gets tripped out it's ok. But I think it would be good to have for IRIDA. Would it be possible to add it as a header after the last column (ie after the "author" field)?

**Comment by ivansg44** [comment]
Yes, it's possible. Should we make it consistent and add it after the author field for the regular format as well?

**Comment by griffie** [comment]
Yeah, sounds good! :)

**Pull request merged**
